# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jibe Style Guides
email: www.jibe.com
description: > # this means to ignore newlines until "baseurl:"
  The Jibe Style Guides represent the base styles for all Jibe products.
  Jibe strives to maintain a clean, modern style in all of it's products to
  emphasize great user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Jibe
github_username:  jibeinc

# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js]
