# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jibe Style Base
description: > # this means to ignore newlines until "baseurl:"
  Living, visual style guide for Jibe Products. Will be integrated over the remainder of 2016. Work in progress.
baseurl: "/jibe-style-base" # the subpath of your site, e.g. /blog
url: "http://jibeinc.github.io" # the base hostname & protocol for your site
twitter_username: jibe
github_username:  jibeinc


# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js]
